name: CI صالون دونير 

on: [push] رفحاء

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |https://goo.gl/maps/H3bHUnGUaBj9YdgW7
        echo Add other actions to build,
        echo test, and deploy your project.
